########
# besu #
########
- source:
    repository: hyperledger/besu
    ref: main
  build_script: ./besu/build.sh
  target:
    tag: main
    repository: ethpandaops/besu
##########
# erigon #
##########
- source:
    repository: ledgerwatch/erigon
    ref: devel
  target:
    tag: devel
    repository: ethpandaops/erigon
##############
# ethereumjs #
##############
- source:
    repository: ethereumjs/ethereumjs-monorepo
    ref: master
  target:
    tag: master
    repository: ethpandaops/ethereumjs
    dockerfile: ./ethereumjs/Dockerfile
########
# geth #
########
- source:
    repository: ethereum/go-ethereum
    ref: master
  target:
    tag: master
    repository: ethpandaops/geth
- source:
    repository: mdehoog/go-ethereum
    ref: eip-4844
  target:
    tag: mdehoog-eip4844
    repository: ethpandaops/geth
##############
# lighthouse #
##############
- source:
    repository: sigp/lighthouse
    ref: stable
  target:
    tag: stable
    repository: ethpandaops/lighthouse
    dockerfile: ./lighthouse/Dockerfile
- source:
    repository: sigp/lighthouse
    ref: capella
  target:
    tag: capella
    repository: ethpandaops/lighthouse
    dockerfile: ./lighthouse/Dockerfile
- source:
    repository: sigp/lighthouse
    ref: stable
  build_script: ./lighthouse/xatu-sentry.sh
  target:
    tag: xatu-sentry
    repository: ethpandaops/lighthouse
    dockerfile: ./lighthouse/Dockerfile
- source:
    repository: sigp/lighthouse
    ref: eip4844
  target:
    tag: eip4844
    repository: ethpandaops/lighthouse
    dockerfile: ./lighthouse/Dockerfile
############
# lodestar #
############
- source:
    repository: chainsafe/lodestar
    ref: unstable
  target:
    tag: unstable
    repository: ethpandaops/lodestar
##############
# nethermind #
##############
- source:
    repository: nethermindeth/nethermind
    ref: master
  target:
    tag: master
    repository: ethpandaops/nethermind
##########
# nimbus #
##########
- source:
    repository: status-im/nimbus-eth2
    ref: unstable
  target:
    tag: unstable
    repository: ethpandaops/nimbus
    dockerfile: ./nimbus/Dockerfile
- source:
    repository: status-im/nimbus-eth2
    ref: unstable
  build_script: ./nimbus/xatu-sentry.sh
  target:
    tag: xatu-sentry
    repository: ethpandaops/nimbus
    dockerfile: ./nimbus/Dockerfile
#########
# prysm #
#########
- source:
    repository: prysmaticlabs/prysm
    ref: latest
  build_script: ./prysm/build.sh
  target:
    tag: latest
    repository: ethpandaops/prysm
    dockerfile: ./prysm/Dockerfile
- source:
    repository: prysmaticlabs/prysm
    ref: develop
  build_script: ./prysm/build.sh
  target:
    tag: develop
    repository: ethpandaops/prysm
    dockerfile: ./prysm/Dockerfile
- source:
    repository: prysmaticlabs/prysm
    ref: master
  build_script: ./prysm/build.sh
  target:
    tag: master
    repository: ethpandaops/prysm
    dockerfile: ./prysm/Dockerfile
- source:
    repository: prysmaticlabs/prysm
    ref: eip4844
  build_script: ./prysm/build.sh
  target:
    tag: eip4844
    repository: ethpandaops/prysm
    dockerfile: ./prysm/Dockerfile
########
# teku #
########
- source:
    repository: consensys/teku
    ref: master
  build_script: ./teku/build.sh
  target:
    tag: master
    repository: ethpandaops/teku
- source:
    repository: consensys/teku
    ref: 4844-interop
  build_script: ./teku/build.sh
  target:
    tag: 4844-interop
    repository: ethpandaops/teku
