name: Install deps
description: Install deps for a source repository

inputs:
  source_repository:
    description: The source repository to build from
    type: string
    required: true

runs:
  using: composite
  steps:
  - name: Checkout this repo
    uses: actions/checkout@v3
  
  - uses: actions/setup-java@v3
    if: contains(inputs.source_repository, 'teku') || contains(inputs.source_repository, 'besu')
    with:
      distribution: 'temurin'
      java-version: '17'
  