name: Manifest
description: Build and push a docker manifest to Docker Hub

inputs:
  platforms:
    description: Comma-separated list of platforms (e.g. linux/amd64,linux/arm64)
    type: string
    required: true
  source_repository:
    description: The source repository to build from
    type: string
    required: true
  source_ref:
    description: The branch, tag or SHA to checkout and build from
    type: string
    required: true
  target_tag:
    description: Docker hub tag to push to
    type: string
    required: true
  target_repository:
    description: Docker hub repository to push to
    type: string
    required: true
  # Secrets
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true

runs:
  using: composite
  steps:
  - name: Checkout this repo
    uses: actions/checkout@v3
  - name: Check out source repository
    uses: actions/checkout@v3
    with:
      repository: ${{ inputs.source_repository }}
      path: source
      ref: ${{ inputs.source_ref }}
  - name: get git commit hash
    id: git_commit_hash
    shell: bash
    run: |
      cd source
      echo "git_commit_hash=$(echo $(git log --pretty=format:'%h' -n 1))" >> $GITHUB_OUTPUT
  - name: Generate images list
    id: generate_images_list
    run: |
      PLATFORMS="${{ inputs.platforms }}"
      IMAGES=""

      IFS=',' read -ra ADDR <<< "$PLATFORMS"
      for platform in "${ADDR[@]}"; do
          slug=$(echo "$platform" | tr '/' '-')
          IMAGES+="${{ inputs.target_repository }}:${{ inputs.target_tag }}-$slug,"
      done

      IMAGES=${IMAGES::-1}  # Remove the trailing comma
      echo "images=$IMAGES" >> $GITHUB_OUTPUT
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ inputs.DOCKER_USERNAME }}
      password: ${{ inputs.DOCKER_PASSWORD }}
  - name: Create and push manifest images
    id: docker_manifest
    uses: Noelware/docker-manifest-action@0.4.0
    with:
      inputs: ${{ inputs.target_repository }}:${{ target_tag }},${{ inputs.target_repository }}:${{ target_tag }}-${{ steps.git_commit_hash.outputs.git_commit_hash }}
      images: ${{ steps.generate_images_list.outputs.images }}
      push: true
  - name: Image digest & tags
    shell: bash
    run: |
      cat << EOF
      digest: ${{ steps.docker_manifest.outputs.images }}
      tags:
        ${{ inputs.target_repository }}:${{ inputs.target_tag }}
        ${{ inputs.target_repository }}:${{ inputs.target_tag }}-${{ steps.git_commit_hash.outputs.git_commit_hash }}
      EOF
