name: Build teku docker image

on:
  workflow_dispatch:
    inputs:
      repository: 
        description: The source teku repository to build from
        default: consensys/teku
        type: string
        required: true
      ref:
        description: The branch, tag or SHA to checkout and build from
        default: master
        type: string
        required: true
      docker_tag:
        description: Override target docker tag (defaults to the above source ref if left blank)
        type: string
        required: false
jobs:
  teku:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: ./.github/actions/deploy.yml
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          build_script: ./teku/build.sh
          target_tag: ${{ inputs.docker_tag || inputs.ref }}
          target_repository: ethpandaops/teku

          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        

