name: Build nimbus docker image

on:
  workflow_dispatch:
    inputs:
      repository: 
        description: The source geth repository to build from
        default: status-im/nimbus-eth2
        type: string
        required: true
      ref:
        description: The branch, tag or SHA to checkout and build from
        default: unstable
        type: string
        required: true
      docker_tag:
        description: Override target docker tag (defaults to the above source ref if left blank)
        type: string
        required: false
      runs_on:
        description: The runner to use
        type: choice
        required: true
        default: ubuntu-latest
        options:
        - ubuntu-latest
        - services-medium-cpu
jobs:
  nimbus:
    uses: ./.github/workflows/deploy.yml
    with:
      source_repository: ${{ inputs.repository }}
      source_ref: ${{ inputs.ref }}
      target_tag: ${{ inputs.docker_tag || inputs.ref }}
      target_repository: ethpandaops/nimbus
      target_dockerfile: ./nimbus/Dockerfile
      runs_on: ${{ inputs.runs_on }}
    secrets:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
