name: Build prysm docker image

on:
  workflow_dispatch:
    inputs:
      repository: 
        description: The source prysm repository to build from
        default: prysmaticlabs/prysm
        type: string
        required: true
      ref:
        description: The branch, tag or SHA to checkout and build from
        default: develop
        type: string
        required: true
      docker_tag:
        description: Override target docker tag (defaults to the above source ref if left blank)
        type: string
        required: false
      runs_on:
        description: The runner to use
        type: choice
        required: true
        default: ubuntu-latest
        options:
        - ubuntu-latest
        - services-medium-cpu

jobs:
  prysm:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
        with:
          repository: ${{ inputs.repository }}
      - uses: ./.github/actions/deploy
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          build_script: ./prysm/build.sh
          target_tag: ${{ inputs.docker_tag || inputs.ref }}
          target_repository: ethpandaops/prysm
          target_dockerfile: ./prysm/Dockerfile

          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      - uses: ./.github/actions/deploy
        with:
          source_repository: ${{ inputs.repository }}
          source_ref: ${{ inputs.ref }}
          build_script: ./prysm/build.sh
          target_tag: ${{ inputs.docker_tag || inputs.ref }}
          target_repository: ethpandaops/prysm-validator
          target_dockerfile: ./prysm/DockerfileValidator

          DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"