name: Build geth docker image


env:
  DEFAULT_REPO: "ethereum/go-ethereum"
  DEFAULT_BRANCH: "master"

on:
  workflow_dispatch:
    inputs:
      reponame:
        description: The geth repo to clone
        default: ethereum/go-ethereum
        required: true
      commitRef:
        description: The branch, tag or SHA to checkout and build from
        default: master
        required: true
  schedule:
    - cron: '0 2 * * *'

jobs:
  git-sync:
    name: git-sync
    # This job runs on Linux
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.reponame || env.DEFAULT_REPO }}
          path: 'geth'
          ref: ${{ github.event.inputs.commitRef || env.DEFAULT_BRANCH }}
      - name: get git commit hash
        id: git_commit_hash
        shell: bash
        run: |
          cd geth
          echo "::set-output name=git-commit-hash::$(echo $(git log --pretty=format:'%h' -n 1))"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker-build-push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./geth
          file: ./geth/Dockerfile
          tags: parithoshj/geth:${{ github.event.inputs.commitRef || env.DEFAULT_BRANCH }}-${{ steps.git_commit_hash.outputs.git-commit-hash }},parithoshj/geth:${{ github.event.inputs.commitRef || env.DEFAULT_BRANCH }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
